### ISSUE TITLE
There are some false positives in cve-2018-7602

### ISSUE THREAD

**Issue by aydcyhr** [zhzyker/vulmap#1]
In the course of testing , I found that there are false positives in cve-2018-7602 . Please try using “python3 vulmap -u http://baidu.com” .In addition , can you write a python file for each vulnerability , just like your exphub project . Danke.

**Comment by zhzyker** [comment]
I have received a lot of similar misinformation and am trying to solve them  
Most false positives are due to the use of all POC,  the "- a" option should be used more often to specify the web type  
"-v" is running separate modules, and I think it's more convenient to integrate them together  

If the manager is enough, do it on both sides

**Comment by aydcyhr** [comment]
Thank you for your reply and look forward to your updated version.
